In [1]:
import pandas as pd

In [90]:
file = pd.read_csv('events_up_to_01062018.csv',low_memory=False)

In [108]:
features_1 = pd.read_csv('features_10.csv')

In [109]:
features_1 = features_1.set_index('person')

In [110]:
precios = pd.read_csv('precios_celulares.csv')

In [111]:
precios.columns=['model','precio']

## Promedio de precios de una region

In [112]:
new_file = file.merge(precios,on='model',how='left')

In [113]:
new_file = new_file.set_index('person').join(features_1,how='left',lsuffix='_left', rsuffix='_right')

In [114]:
a=new_file.loc[new_file['event']=='viewed product'].groupby('region_sin_unknown')["precio"].mean().to_frame().reset_index()
a.columns=['region_sin_unknown','precio_visto_promedio_region']

In [115]:
b=new_file.loc[new_file['event']=='conversion'].groupby('region_sin_unknown')["precio"].mean().to_frame().reset_index()
b.columns=['region_sin_unknown','precio_compras_promedio_region']

In [116]:
features_1=features_1.reset_index()

In [117]:
features_1= features_1.merge(a,on="region_sin_unknown",how='left')
features_1= features_1.merge(b,on="region_sin_unknown",how='left')

## Diferencia de precios entre el promedio de la region y el usuario

In [118]:
features_1["diferencia_con_la_region"] = features_1['precio_visto_promedio_region']-features_1["promedio_precio_celulares_vistos"]

In [119]:
features_1["diferencia_con_la_region_n"] = (features_1["diferencia_con_la_region"] - features_1["diferencia_con_la_region"].mean() ) / features_1["diferencia_con_la_region"].std()

In [120]:
features_1.head()

,person,mayor_evento,prod_visto,dispos,compras,visitas,cant_prod_vistos,primer_visita,ultima_visita,cant_eventos,...,pais_sin_unknown,precio_del_cel_mas_visto,promedio_precio_celulares_vistos,promedio_precio_celulares_comprados,precio_mas_caro_que_vio,precio_mas_barato_que_vio,precio_visto_promedio_region,precio_compras_promedio_region,diferencia_con_la_region,diferencia_con_la_region_n
0,0008ed71,checkout,Ninguno,Computer,0,2,0,05-17,05-17,6,...,Brazil,NaN,NaN,0.0,NaN,NaN,1241.739781,893.583301,NaN,NaN
1,00091926,viewed product,iPhone 6S,Computer,0,34,372,05-03,05-31,448,...,Brazil,1679.0,1527.091398,0.0,4649.0,100.0,1263.412702,994.158371,-263.678696,-0.494987
2,00091a7a,brand listing,iPhone 6S,Smartphone,0,1,3,03-26,03-26,10,...,Brazil,1679.0,1342.333333,0.0,1679.0,849.0,1160.083348,932.511551,-182.249986,-0.363554
3,000ba417,viewed product,Samsung Galaxy A3 Duos,Computer,1,6,153,05-17,05-26,206,...,Brazil,369.0,479.366013,379.0,2229.0,250.0,1241.739781,893.583301,762.373768,1.161142
4,000c79fe,searched products,iPhone 7,Smartphone,0,1,3,05-29,05-29,17,...,Brazil,2229.0,2229.000000,0.0,2229.0,2229.0,1160.083348,932.511551,-1068.916652,-1.794704

In [122]:
features_1.to_csv("features_11.csv")

## Clean features que no aportan

In [2]:
features = pd.read_csv("features_11.csv", low_memory=False)

In [47]:
labels = pd.read_csv("labels_training_set.csv", low_memory=False)

In [71]:
labels["label"].value_counts()

0    18434
1      980
Name: label, dtype: int64

#### Listado de features hasta ahora

In [4]:
for i in features.columns:
    print (i)

Unnamed: 0
person
mayor_evento
prod_visto
dispos
compras
visitas
cant_prod_vistos
primer_visita
ultima_visita
cant_eventos
permanencia
hace_cuanto_visito
eventos_por_dia
channel
vio_celulares
region
is_new
personas_mismo_prod_visto
opsis
scrnres
personas_mismo_mayor_evento
personas_mismo_disp
personas_mismo_region
personas_mismo_channel
primer_channel
lead_1
personas_mismo_opsis
personas_mismo_scrnres
busco_productos
clickeo_ad
hizo_checkout
entro_desde_motor
hizo_conversion
filtro_busquedas
busco_marca
visito_sitio
hizo_lead
primer_evento
modelos_distintos
busquedas
clicks_en_ads
checkouts
entradas_desde_motor
listar_productos
listar_marca
tamanio_pantalla
entro_direct
uso_computer
viewed product
searched products
ad campaign hit
staticpage
checkout
search engine hit
conversion
generic listing
brand listing
visited site
lead
Excelente
Muito Bom
Bom
Bom - Sem Touch ID
Novo
32GB
64GB
128GB
16GB
8GB
256GB
4GB
512MB
Conditions
AboutUs
how-to-sell
trust-trocafone
how-to-buy
CustomerService
club-trocafone
Quiosks
FaqEcommerce
TermsAndConditionsReturnEcommerce
TermsAndConditionsEcommerce
galaxy-s8
PrivacyEcommerce
black_friday
Google
Yahoo
Bing
Ask
Smartphone
Computer
Tablet
Unknown
Paid
Organic
Direct
Referral
Social
Email
Unknown.1
0
1
2
3
4
5
6
Excelente_compro
Excelente_vio
Muito Bom_compro
Muito Bom_vio
Bom_compro
Bom_vio
Bom - Sem Touch ID_compro
Bom - Sem Touch ID_vio
Novo_compro
Novo_vio
32GB_compro
32GB_vio
64GB_compro
64GB_vio
128GB_compro
128GB_vio
16GB_compro
16GB_vio
8GB_compro
8GB_vio
256GB_compro
256GB_vio
4GB_compro
4GB_vio
512MB_compro
512MB_vio
region_sin_unknown
pais_sin_unknown
precio_del_cel_mas_visto
promedio_precio_celulares_vistos
promedio_precio_celulares_comprados
precio_mas_caro_que_vio
precio_mas_barato_que_vio
precio_visto_promedio_region
precio_compras_promedio_region
diferencia_con_la_region
diferencia_con_la_region_n

In [13]:
lista_no_sirven=[]

In [14]:
lista_no_sirven.append("Ask")

In [25]:
features["Unknown.1"].value_counts()

0    38826
4        1
2        1
1        1
Name: Unknown.1, dtype: int64

In [50]:
inn=features.loc[features["Unknown.1"].isin([4,2,1])]
inn

,Unnamed: 0,person,mayor_evento,prod_visto,dispos,compras,visitas,cant_prod_vistos,primer_visita,ultima_visita,...,pais_sin_unknown,precio_del_cel_mas_visto,promedio_precio_celulares_vistos,promedio_precio_celulares_comprados,precio_mas_caro_que_vio,precio_mas_barato_que_vio,precio_visto_promedio_region,precio_compras_promedio_region,diferencia_con_la_region,diferencia_con_la_region_n
24322,24322,a0d795fb,viewed product,Samsung Galaxy Note 4,Smartphone,0,2,6,05-20,05-26,...,Brazil,989.0,905.833333,0.0,1629.0,390.0,1241.739781,893.583301,335.906447,0.472790
32476,32476,d67688d9,checkout,Samsung Galaxy Gran 2 Duos TV,Smartphone,1,5,9,05-28,05-30,...,Brazil,150.0,316.333333,150.0,649.0,150.0,1151.030020,823.768786,834.696686,1.277877
36557,36557,f12bd42e,viewed product,iPhone 7,Computer,1,43,710,03-19,05-15,...,Brazil,2229.0,1702.098592,1499.0,3869.0,499.0,1177.591443,832.759259,-524.507149,-0.915984

No se sabe bien que es es esta columna, ni porque aparece pero la mayoria de sus datos son cero.
Me fijo si realizaron una conversion las personas con los valores no nulos

In [55]:

joined=labels.set_index("person").join(inn.set_index("person"),how="right")

In [56]:
joined

,label,Unnamed: 0,mayor_evento,prod_visto,dispos,compras,visitas,cant_prod_vistos,primer_visita,ultima_visita,...,pais_sin_unknown,precio_del_cel_mas_visto,promedio_precio_celulares_vistos,promedio_precio_celulares_comprados,precio_mas_caro_que_vio,precio_mas_barato_que_vio,precio_visto_promedio_region,precio_compras_promedio_region,diferencia_con_la_region,diferencia_con_la_region_n
person,,,,,,,,,,,,,,,,,,,,,
a0d795fb,0.0,24322,viewed product,Samsung Galaxy Note 4,Smartphone,0,2,6,05-20,05-26,...,Brazil,989.0,905.833333,0.0,1629.0,390.0,1241.739781,893.583301,335.906447,0.472790
d67688d9,NaN,32476,checkout,Samsung Galaxy Gran 2 Duos TV,Smartphone,1,5,9,05-28,05-30,...,Brazil,150.0,316.333333,150.0,649.0,150.0,1151.030020,823.768786,834.696686,1.277877
f12bd42e,NaN,36557,viewed product,iPhone 7,Computer,1,43,710,03-19,05-15,...,Brazil,2229.0,1702.098592,1499.0,3869.0,499.0,1177.591443,832.759259,-524.507149,-0.915984

Su aparicion no pareciera tener nada que ver con la columna de compra

In [57]:
lista_no_sirven.append("Unknown.1")

In [58]:
lista_no_sirven.append("diferencia_con_la_region_n")

In [67]:
lista_no_sirven.append("Unnamed: 0")

In [62]:
features["Bing"].value_counts()

0     38545
1       149
2        61
3        27
4        18
5        11
7         5
11        3
9         3
6         2
17        1
15        1
10        1
40        1
8         1
Name: Bing, dtype: int64

Ok. Aca pareciera haber algo mas interesante, pruebo ver contra los labels

In [65]:
inn = features.loc[features["Bing"] != 0 ]

In [73]:
joined=labels.set_index("person").join(inn.set_index("person"),how="right")
a=joined.dropna().loc[joined["label"]== 1.0]

In [74]:
a["Bing"]

person
15de4f10     2
2f729bc3    17
34c139ce     7
412c10b7     1
6e41e5e3     3
90ab4ff1     2
9112e797     1
9321b788     2
a1182406     1
b71798a7     1
b866afff     4
ddc538e7     1
fc163c0f     1
Name: Bing, dtype: int64

No la borraria ya que algunos de los que buscan por bing terminan dando label 1

In [81]:
lista_automatizada=[]

In [83]:
for elem in features.columns:
    inn = features.loc[features[elem] != 0 ]
    joined=labels.set_index("person").join(inn.set_index("person"),how="right")
    a=joined.dropna().loc[joined["label"]== 1.0]
    if len(a)==0:
        lista_automatizada.append(elem)

In [89]:
lista_automatizada

['PrivacyEcommerce',
 'Ask',
 'Unknown',
 'Unknown.1',
 'Novo_compro',
 '256GB_compro']

In [107]:
features=features.drop(lista_automatizada,axis=1)

In [108]:
features= features.drop(lista_no_sirven,axis=1)

features mas importantes (ojo el overfitting)

In [116]:
lista_mas_imp=[]
for elem in features.columns:
    inn = features.loc[features[elem] != 0 ]
    joined=labels.set_index("person").join(inn.set_index("person"),how="right")
    a=joined.dropna().loc[joined["label"]== 1.0]
    if len(a)>912:
        lista_mas_imp.append(elem)

In [120]:
f=features.loc[:,lista_mas_imp].set_index("person")

In [123]:
features = features.set_index("person")
features.head()

,mayor_evento,prod_visto,dispos,compras,visitas,cant_prod_vistos,primer_visita,ultima_visita,cant_eventos,permanencia,...,region_sin_unknown,pais_sin_unknown,precio_del_cel_mas_visto,promedio_precio_celulares_vistos,promedio_precio_celulares_comprados,precio_mas_caro_que_vio,precio_mas_barato_que_vio,precio_visto_promedio_region,precio_compras_promedio_region,diferencia_con_la_region
person,,,,,,,,,,,,,,,,,,,,,
0008ed71,checkout,Ninguno,Computer,0,2,0,05-17,05-17,6,1,...,Sao Paulo,Brazil,NaN,NaN,0.0,NaN,NaN,1241.739781,893.583301,NaN
00091926,viewed product,iPhone 6S,Computer,0,34,372,05-03,05-31,448,28,...,Rio Grande do Sul,Brazil,1679.0,1527.091398,0.0,4649.0,100.0,1263.412702,994.158371,-263.678696
00091a7a,brand listing,iPhone 6S,Smartphone,0,1,3,03-26,03-26,10,1,...,Minas Gerais,Brazil,1679.0,1342.333333,0.0,1679.0,849.0,1160.083348,932.511551,-182.249986
000ba417,viewed product,Samsung Galaxy A3 Duos,Computer,1,6,153,05-17,05-26,206,10,...,Sao Paulo,Brazil,369.0,479.366013,379.0,2229.0,250.0,1241.739781,893.583301,762.373768
000c79fe,searched products,iPhone 7,Smartphone,0,1,3,05-29,05-29,17,1,...,Minas Gerais,Brazil,2229.0,2229.000000,0.0,2229.0,2229.0,1160.083348,932.511551,-1068.916652

In [124]:
features.to_csv("features_12.csv")